Build Sidebar
syllapedia/syllapedia pull request #12
Opened 2024-01-09 20:05 UTC by attilapalabiyik

* Created sidebar
* Created saved, search, and create tabs
* Created saved courses content with selection functionality
* Created create course popup with an interactive editor
* Created subject, number, and title input for searching and editing
* Standardized course naming and renamed gemini and openai files
* Fixed user course get function to return courses as objects instead of ids

2024-01-15 20:59 UTC, algispetlin requested changes

2024-01-15 20:59 UTC, algispetlin commented on frontend/src/components/CourseNameView.css
> +    font-size: 1.5em;
Why is this in em while everything else is in px?

2024-01-15 20:59 UTC, algispetlin commented on frontend/src/components/CourseSearch.tsx
> +    const [subject, setSubject] = useState("");
You could combine these three state variables into one. For example: const[{ subject: string, number: string, title: string }] = useState({ subject: "", number: "", title: "" });

2024-01-15 20:59 UTC, algispetlin commented on frontend/src/components/CourseSearch.tsx
> +    const handleSubject = (value: string | null) => {
Make this a ternary

2024-01-15 20:59 UTC, algispetlin commented on frontend/src/components/CourseSearch.tsx
> +    const handleNumber = (value: string | null) => {
Also make this a ternary

2024-01-15 20:59 UTC, algispetlin commented on frontend/src/components/CourseSearch.tsx
> +    const handleTitle = (value: string | null) => {
Also make this a ternary

2024-01-15 20:59 UTC, algispetlin commented on frontend/src/components/CreateDialog.tsx
> +    const [subjectNameToCode, setSubjectNameToCode] = useState<Record<string, string>>(({'Accounting': 'ACCOUNTG', 'Aerospace Studies': 'AEROSPAC', 'Afro-American Studies': 'AFROAM', 'Animal Science'
Like I mentioned before, combine these into one state. Also, create an interface in courseModels.ts that stores this information as an enum. Look up what an enum is if you don't know what I'm talking about.

2024-01-15 20:59 UTC, algispetlin commented on frontend/src/components/CreateDialog.tsx
> +    const handleSubject = (value: string | null) => {
Make this a ternary

2024-01-15 20:59 UTC, algispetlin commented on frontend/src/components/CreateDialog.tsx
> +    const handleNumber = (value: string | null) => {
Make this a ternary

2024-01-15 20:59 UTC, algispetlin commented on frontend/src/components/CreateDialog.tsx
> +    const handleTitle = (value: string | null) => {
Make this a ternary

2024-01-15 20:59 UTC, algispetlin commented on frontend/src/components/CreateDialog.tsx
> +	const handleSyllabus = (event: React.ChangeEvent<HTMLInputElement>) => {
Fix indentation

2024-01-15 20:59 UTC, algispetlin commented on frontend/src/components/CreateDialog.tsx
> +        <Dialog open={open} onClose={() => escape()}>
Do onClose={escape}

2024-01-15 20:59 UTC, algispetlin commented on frontend/src/components/CreateDialog.tsx
> +                    <Grid item xs={12}><div style={{height:"35px"}}></div></Grid>
What is the point of this empty div?

2024-01-15 20:59 UTC, algispetlin commented on frontend/src/components/CreateDialog.tsx
> +                        <Button size="medium" variant="contained" color="primary" onClick={() => createCourse()}>
onClick={createCourse}

2024-01-15 20:59 UTC, algispetlin commented on frontend/src/components/MainLayout.tsx
> -            <Navbar />
You can just hide the navbar when you are on the login page instead of deleting it from the MainLayout. We need the Navbar on all other pages

2024-01-15 20:59 UTC, algispetlin commented on frontend/src/components/SavedCourses.tsx
> +function SavedCourses({userId, userCourses, selectedCourse, setSelectedCourse}: {userId: string, userCourses: CourseInfo[], selectedCourse: {name: string, instructor: string}, setSelectedCourse: ({na
Make an interface to deal with all these types and properties. It looks messy to include it in the function definition like this

2024-01-15 20:59 UTC, algispetlin commented on frontend/src/components/SavedTab.tsx
> +function SavedTab({open, handleSavedClick}: {open: boolean, handleSavedClick: () => void}) {
Create an interface

2024-01-15 20:59 UTC, algispetlin commented on frontend/src/components/Sidebar.css
> +    height: calc(100vh - var(--num-tabs) * var(--tab-height) - var(--divider-height));
Why are you using vh instead of px or % like is used everywhere else?

2024-01-15 20:59 UTC, algispetlin commented on frontend/src/components/Sidebar.tsx
> +                    {user.user && (user.user.permission === "instructor" || user.user.permission === "admin") &&
Delete the excess <></>

2024-01-15 20:59 UTC, algispetlin commented on frontend/src/components/SubjectDropdown.tsx
> +    const [subjectNameToCode, setSubjectNameToCode] = useState<Record<string, string>>(({'Accounting': 'ACCOUNTG', 'Aerospace Studies': 'AEROSPAC', 'Afro-American Studies': 'AFROAM', 'Animal Science'
As mentioned before, move this stuff to courseModels.ts as an enum. This looks messy

2024-01-15 20:59 UTC, algispetlin commented on frontend/src/components/UploadSyllabus.tsx
> +function UploadSyllabus({syllabus, handleSyllabus, size}: {syllabus: string, handleSyllabus: (event: React.ChangeEvent<HTMLInputElement>) => void, size: "small" | "medium"}) {
Create an interface

2024-01-15 20:59 UTC, algispetlin commented on frontend/src/pages/ChatPage.tsx
> +        <div className="root">
Display the sidebar and navbar on MainLayout and hide them only on certain pages

2024-01-15 20:59 UTC, algispetlin commented on frontend/src/services/httpService.ts
> +const FLASK_URL = 'http://localhost:5000'
FLASK_URL should always be using azure on commit

2024-01-16 21:52 UTC, attilapalabiyik commented on frontend/src/components/Sidebar.css
> +    height: calc(100vh - var(--num-tabs) * var(--tab-height) - var(--divider-height));
vh is meant to represent the height of the sidebar, but the height of the sidebar is always 100%. As a result, it is changed now.

2024-01-16 21:59 UTC, attilapalabiyik commented on frontend/src/components/Sidebar.css
> +    height: calc(100vh - var(--num-tabs) * var(--tab-height) - var(--divider-height));
The parent of tab-content is a collapsible, not the sidebar. As a result, 100% is the height of the collapsible as opposed to the sidebar. vh is the height of the viewport which is the height of the sidebar.

2024-01-16 23:08 UTC, attilapalabiyik commented on frontend/src/components/CreateDialog.tsx
> +                    <Grid item xs={12}><div style={{height:"35px"}}></div></Grid>
It is a spacer.

2024-01-16 23:18 UTC, algispetlin approved these changes

2024-01-16 23:21 UTC, merged